name: Optimize resource pack
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Version
        id: set_version
        run: |
          latest_version=$(git tag -l --sort=v:refname | tail -n1)

          if [[ $latest_version =~ ^v([0-9]+)\.([0-9]+)$ ]]; then
            major=$((10#${BASH_REMATCH[1]}))
            minor=$((10#${BASH_REMATCH[2]}))
          else
            echo "Invalid version format"
            exit 1
          fi

          # Increment minor version
          minor=$((minor + 1))

          new_version="v${major}.${minor}"
          echo "Setting new version: ${new_version}"

          echo "::set-output name=new_version::${new_version}"
        shell: bash

      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.new_version }}
          files: /tmp/pack.zip
