name: Optimize resource pack
on: [push]
permissions:
  contents: write
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'main'
            output_file_path = '/tmp/pack.zip'
      - name: Set Version
        id: set_version
        run: |
          current_version=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*")
          echo "Current version: ${current_version}"
          version_parts=(${current_version//./ })
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}

          if [ -z "$patch" ]; then
            patch=0
          else
            patch=$((patch + 1))
          fi

          # Check if it's time to increment the major version
          if [ "$major" -eq 0 ] && [ "$minor" -eq 9 ] && [ "$patch" -eq 10 ]; then
            major=$((major + 1))
            minor=0
            patch=0
          elif [ "$patch" -eq 10 ]; then
            minor=$((minor + 1))
            patch=0
          fi

          new_version="${major}.${minor}.${patch}"
          echo "Setting new version: ${new_version}"

          echo "::set-output name=new_version::${new_version}"
        shell: bash
          
      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.new_version }}
          files: /tmp/pack.zip
