name: Optimize resource pack
on: [push]
permissions:
  contents: write
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Set Version
        id: set_version
        run: |
          current_version=$(git describe --tags --abbrev=0)
          echo "Current version: ${current_version}"

          # Extract major, minor, and patch using regex
          if [[ $current_version =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=$((10#${BASH_REMATCH[1]}))
            minor=$((10#${BASH_REMATCH[2]}))
            patch=$((10#${BASH_REMATCH[3]}))
          else
            echo "Invalid version format"
            exit 1
          fi

          # Increment patch version
          patch=$((patch + 1))

          # Increment minor version if patch is 10
          if [ "$patch" -eq 10 ]; then
            minor=$((minor + 1))
            patch=0
          fi

          # Increment major version if minor is 10
          if [ "$minor" -eq 10 ]; then
            major=$((major + 1))
            minor=0
          fi

          new_version="v${major}.${minor}.${patch}"
          echo "Setting new version: ${new_version}"

          echo "::set-output name=new_version::${new_version}"
        shell: bash
          
      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.new_version }}
          files: /tmp/pack.zip
          